# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: TS+React 19 test
        run: ./run-test.sh integrations/ts-react19
      - name: TS+React 18 test
        run: ./run-test.sh integrations/ts-react18
      - name: TS+React 16 test
        run: ./run-test.sh integrations/ts-react16
      - name: TS4+React 17 test
        run: ./run-test.sh integrations/ts4-react17
